name: CI

# Workflow file for windows
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  MSYS2:
    name: Windows-msys2-mingw32
    runs-on: [windows-latest]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Install MSYS2 with MinGW 32-bit
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32 # D2TM is built within a MinGW32 bit environment
          update: true
          install: mingw-w64-i686-gcc mingw-w64-i686-binutils mingw-w64-i686-cmake mingw-w64-i686-make git
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Configure
        run: |
          cd "${{ github.workspace }}"
          mkdir build
          cd build
          cmake .. -G "MinGW Makefiles"
      - name: Build
        run: |
          cd "${{ github.workspace }}\build"
          make -j -l 3